# ports:
# - adminer : 8080:8080
# - db : 8084:3306
# - server:
# - API :
# - Program :

# username: root
# password: P@ssw0rd

services:
  db:
    image: "maacke16/vteam-db:latest"
    container_name: "database"
    ports:
      - "8084:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "vteampass"
    volumes:
      - "./database:/backups/"

    command: ["/bin/bash", "./backup.sh"]

# database interface
  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    ports:
      - 8080:8080

# backend (server)
  server:
    image: "maacke16/vteam-server:latest"
    container_name: "backend"
    ports:
      - "8083:1338"
    restart: always