networks:
  vteams:

services:
  server:
    image: ""
    container_name: "server"
    ports:
      - "8080:80"
    volumes:
      - ""
    restart:
      "always"
    networks:
      vteams:

  client:
    image: ""
    container_name: ""
    networks:
      vteams:
  
  database:
    image: ""
    container_name: "database"
    ports:
      - "3306:3306"
    networks:
      vteams: