name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'server/**'
      - 'database/**'
      - 'client/**'
      - 'program/**'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: maacke16
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: ./server/
          push: true
          tags: maacke16/vteam-server

      - name: Build and push database image
        uses: docker/build-push-action@v4
        with:
          context: ./database/
          push: true
          tags: maacke16/vteam-db

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./api/
          push: true
          tags: maacke16/vteam-api

      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: ./client/
          push: true
          tags: maacke16/vteam-client

      - name: Build and push program image
        uses: docker/build-push-action@v4
        with:
          context: ./program/
          push: true
          tags: maacke16/vteam-program