name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'server/**'
      - 'database/**'
      - 'client/**'
      - 'program/**'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: maacke16
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Push Images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            maacke16/vteam-server:latest
            maacke16/vteam-db:latest
            maacke16/vteam-api:latest
            maacke16/vteam-client:latest
            maacke16/vteam-program:latest
          context: |
            ./server/
            ./database/
            ./api/
            ./client/
            ./program/
