name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'server/Dockerfile'
      - 'database/Dockerfile'
      - 'client/Dockerfile'
      - 'program/Dockerfile'
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./server/ -t maacke16/vteam-server:latest
          docker build ./database/ -t maacke16/vteam-db:latest
          docker build ./api/ -t maacke16/vteam-api:latest
          docker build ./client/ -t maacke16/vteam-client:latest
          docker build ./program/ -t maacke16/vteam-program:latest
      - name: push image
        run: |
          docker login -u maacke16 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push maacke16/vteam-server:latest
          docker push maacke16/vteam-db:latest
          docker push maacke16/vteam-api:latest
          docker push maacke16/vteam-client:latest
          docker push maacke16/vteam-program:latest